#include "pch.h"
#include "resource.h"
#include "version.hpp"
#include "app_interface.hpp"
#include "hive.hpp"
#include "utils.hpp"
#include "debug.hpp"
#include "table/reader.hpp"
#include "table/entry.hpp"
#include "table/manager.hpp"
#include "table/entry/project.hpp"
#include "table/entry/video_size.hpp"
#include "table/entry/video_rate.hpp"
#include "table/entry/audio_rate.hpp"
#include "table/entry/scene_name.hpp"
#include "table/entry/layer_name.hpp"
#include "dialog/manager.hpp"
#include "dialog/entity/new_project.hpp"
#include "dialog/entity/set_layer_name.hpp"
#include "hook/entry.hpp"
#include "hook/manager.hpp"
#include "hook/entry/call_wnd_proc_ret.hpp"
#include "config_dialog.hpp"
#include "config_io.hpp"
#include "app.hpp"

namespace apn::preset_adder
{
}
